# This file was generated by GoReleaser. DO NOT EDIT.
cask "storm" do
  name "storm"
  desc "A changelog manager with TUIs for review and release"
  homepage "https://github.com/stormlightlabs/git-storm"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "storm"
  manpage "manpages/storm.1"
  bash_completion "completions/storm.bash"
  zsh_completion "completions/storm.zsh"
  fish_completion "completions/storm.fish"

  on_macos do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "9bfc5942f6c2c21972f9b295bf945ca85a3f447c44877134751bb551ff7cf14c"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "b446abec18c2009a0bd125af98fc6504567cfe81a1c6187c1d4fffd901f40c05"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "cb706187b3b63a7a10f3d1d3ca4c349eeb2e1d2506fce20788d863b249285137"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "3562b601333ba60ca484d1135c884a77b00649b441a915067fb8991a2978ff75"
    end
  end

  # No zap stanza required
end
