# This file was generated by GoReleaser. DO NOT EDIT.
cask "storm" do
  name "storm"
  desc "A changelog manager with TUIs for review and release"
  homepage "https://github.com/stormlightlabs/git-storm"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "storm"
  manpage "manpages/storm.1"
  bash_completion "completions/storm.bash"
  zsh_completion "completions/storm.zsh"
  fish_completion "completions/storm.fish"

  on_macos do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "b13b8acb6fe33c6318d3e42fd2c29c2f807766aa7d8ca3c6179e7d60aa24c94f"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "898daa6e9f762632c4a0cd2fb22fb6accd48feac851a348a903928a0da51a2b0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "28ba93d2489a66b2c694b281f6f271c75fbc1d6081727fae9b4dd05c7182235f"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "8ab9a3673853b79d0e0b7c169c44e5f625d036a53550ddd92295f138c240f8de"
    end
  end

  # No zap stanza required
end
