# This file was generated by GoReleaser. DO NOT EDIT.
cask "storm" do
  name "storm"
  desc "A changelog manager with TUIs for review and release"
  homepage "https://github.com/stormlightlabs/git-storm"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "storm"
  manpage "manpages/storm.1"
  bash_completion "completions/storm.bash"
  zsh_completion "completions/storm.zsh"
  fish_completion "completions/storm.fish"

  on_macos do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "7a457ad1b88b396bc0eb97f35a2230abae8537b84c5700ce24558fc371f438cc"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "ec2382422dd7287a409f8e124fceaeddfd46b4fc2ed6aa8728e762743828ab19"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "ed8e453148d44db892587083a0b59e02a49a7e975a9b197796ca5f146827376e"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "b91faa30380394a173122c4d4767347b81ce7320dd832323f1da1efb6645b2a5"
    end
  end

  # No zap stanza required
end
