# This file was generated by GoReleaser. DO NOT EDIT.
cask "storm" do
  name "storm"
  desc "A changelog manager with TUIs for review and release"
  homepage "https://github.com/stormlightlabs/git-storm"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "storm"
  manpage "manpages/storm.1"
  bash_completion "completions/storm.bash"
  zsh_completion "completions/storm.zsh"
  fish_completion "completions/storm.fish"

  on_macos do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "38d499784e1cda82d0e23bd92c13f1738c7f21455d147ea5fb3a50aebdb5010c"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "c409d7b6d758b50c5acb04e15e1e7b27197666abceed7fd7d7fcfdfffccb1f44"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "e515028aa49c2e62e0b2e6dd131fbc4e5f448f38669d4ff07b50578fb7f57b6b"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "c57a826d1f1ed9ec0b6bf9798201b06758fc1786081148b00e355f94e2d7131d"
    end
  end

  # No zap stanza required
end
