# This file was generated by GoReleaser. DO NOT EDIT.
cask "storm" do
  name "storm"
  desc "A changelog manager with TUIs for review and release"
  homepage "https://github.com/stormlightlabs/git-storm"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "storm"
  manpage "manpages/storm.1"
  bash_completion "completions/storm.bash"
  zsh_completion "completions/storm.zsh"
  fish_completion "completions/storm.fish"

  on_macos do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "ce7887f54be25900bedf7829b20a4e0bed8bdc60e114cd91fe9cb7cc8250193f"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "2f9ea32d60ee1b592f3541f1f74a18d2b4849e3c44e723b3e5e52f63c265c556"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "88d03711582f1321ed718ae24ce5dbb5b7a420bd9f7cfc4318047ecb09813c86"
    end
    on_arm do
      url "https://github.com/stormlightlabs/git-storm/releases/download/v#{version}/git-storm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/stormlightlabs/git-storm/"
      sha256 "01c89092a86573f513ee7d307214c35a513a8139f6c3505d2dbef6cb9c010686"
    end
  end

  # No zap stanza required
end
